name: Update README and Site

on:
  push:
    paths:
      - 'data/vouchers.js'
  workflow_dispatch:

jobs:
  update-content:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Generate README
        run: node scripts/generate-readme.js

      - name: Update site
        run: node scripts/update-site.js

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
          publish_branch: gh-pages
          full_commit_message: Update site from voucher data

      - name: Commit changes to main
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add README.md index.html
          git diff --quiet && git diff --staged --quiet || git commit -m "Update README and site from voucher data"
          git push